"""
CLI init command — interactive entity initialisation.

Handles:
  - New entity creation from fcp-ref templates
  - Existing entity reset-to-FAP and selective update flows
  - .fcp-entity marker, baseline.json, runtime directory creation
  - Optional git init and initial commit
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

from ..store import (
    API_KEY_ENV, atomic_write, read_json, save_api_key,
    FCP_HOME, entity_root_for, list_entities,
    get_default_entity, set_default_entity,
)
from .. import ui


def read_fcp_version(fcp_ref_root: Path) -> str:
    """Read FCP version from pyproject.toml in fcp_ref_root."""
    try:
        import re
        text = (fcp_ref_root / "pyproject.toml").read_text(encoding="utf-8")
        m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
        if m:
            return m.group(1)
    except Exception:
        pass
    return "unknown"


def write_entity_gitignore(entity_root: Path) -> None:
    """Write a .gitignore tailored for an FCP entity root."""
    content = """\
# FCP entity root — generated by fcp init

# Volatile runtime artefacts — do not commit
io/inbox/
io/spool/
state/sentinels/
state/snapshots/
state/operator_notifications/
state/integrity.log
state/distress.beacon
state/first-stimuli.json
state/pending-closure.json

# Python
__pycache__/
*.py[cod]

# Environment / secrets
.env
.fcp.env
"""
    gitignore = entity_root / ".gitignore"
    gitignore.write_text(content, encoding="utf-8")


def _get_allowed_backends(profile: str) -> list[str]:
    from ..cpe.base import BACKENDS
    if profile == "haca-evolve":
        return BACKENDS
    return [b for b in BACKENDS if b != "pairing"]


def run_init(fcp_ref_root: Path) -> None:
    """Interactive init — creates a new entity root from fcp-ref templates."""
    fcp_version = read_fcp_version(fcp_ref_root)

    print()
    ui.hr()
    print(f"  FCP — Filesystem Cognitive Platform v{fcp_version}")
    print(f"  HACA — Host-Agnostic Cognitive Architecture v1.0")
    ui.hr()
    print(f"  FCP is a reference implementation of HACA and may contain")
    print(f"  errors. HACA is an open architecture specification for")
    print(f"  persistent cognitive entities.")
    print()
    print(f"  Contributions are welcome. Report issues and security")
    print(f"  vulnerabilities at: https://github.com/HACA-org/HACA")
    ui.hr()
    print()
    ui.print_warn("WARNING: EXPERIMENTAL SYSTEM")
    ui.hr()
    print(f"  Despite integrated safety mechanisms, this is experimental")
    print(f"  software. Use may result in data loss, host environment")
    print(f"  damage, or leakage of sensitive information.")
    print()
    print(f"  Do not use in production without a prior security review.")
    print(f"  By continuing, you acknowledge and accept these risks.")
    ui.hr()
    print()
    if not ui.confirm("Continue?"):
        sys.exit(0)

    # ── Step 1: Entity ID ────────────────────────────────────────────────────
    ui.hr("1. Entity ID")
    print()
    print(f"  Entities are installed at {FCP_HOME}/<entity_id>/")
    print()

    existing = list_entities()
    if existing:
        print("  Existing entities:")
        default = get_default_entity()
        for eid in existing:
            marker = "  (default)" if eid == default else ""
            print(f"    {eid}{marker}")
        print()

    entity_id_input = ui.ask("Entity ID", "my-entity")
    entity_id = entity_id_input.strip().lower().replace(" ", "-")
    if not entity_id or "/" in entity_id or "\\" in entity_id or ".." in entity_id:
        ui.print_err("Invalid entity ID. Use a simple identifier (e.g. my-entity).")
        sys.exit(1)

    entity_root = entity_root_for(entity_id)

    is_fcp_entity = (entity_root / ".fcp-entity").exists() or (entity_root / "state" / "baseline.json").exists()

    if is_fcp_entity:
        print()
        ui.print_warn(f"Existing FCP entity detected at {entity_root}.")
        action_items = [
            "Factory reset — wipe entity_root/ and re-initialise from scratch",
            "Cancel",
        ]
        choice_label = ui.pick_one("Select an action", action_items, default_idx=1, indent="  ")
        choice_idx = action_items.index(choice_label)

        if choice_idx == 1:
            sys.exit(0)

        # Factory reset: wipe all content, then fall through to profile selection
        ui.hr("Factory reset")
        print()
        print(f"  Wiping {entity_root} ...")
        for item in entity_root.iterdir():
            if item.name == ".git":
                continue
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()
        ui.print_ok("Entity wiped. Re-initialising...")
        print()

    # ── Step 2: Profile ─────────────────────────────────────────────────────
    ui.hr("2. Profile")
    print()
    print("  HACA-Core — Zero-autonomy")
    print("    Every structural change and evolution requires explicit Operator")
    print("    approval. Designed for enterprise and adversarial environments.")
    print()
    print("  HACA-Evolve — Supervised autonomy")
    print("    The entity acts and evolves independently within a declared scope,")
    print("    under Operator supervision. Designed for long-term assistants")
    print("    and companions.")
    print()
    profile_items = [
        "HACA-Core   — Zero-autonomy",
        "HACA-Evolve — Supervised autonomy",
    ]
    profile_choice = ui.pick_one("Profile", profile_items, default_idx=0, indent="  ")
    profile = "haca-core" if profile_items.index(profile_choice) == 0 else "haca-evolve"
    haca_profile = "HACA-Core-1.0.0" if profile == "haca-core" else "HACA-Evolve-1.0.0"

    # ── Step 3: Evolve scope ─────────────────────────────────────────────────
    evolve_scope: dict = {}
    if profile == "haca-evolve":
        ui.hr("3. Autonomous scope")
        print()
        print("  Define what this entity is authorised to do autonomously.")
        print("  These permissions can be revoked by re-initialising.")
        print()

        print("  [1] Autonomous structural evolution")
        print("      The entity may modify its own entity root freely, including")
        print("      its own code. WARNING: this grants unrestricted write access")
        print("      to the entire entity root.")
        allow_evolution = ui.confirm("Authorise?", indent="      ")

        print()
        print("  [2] Autonomous skill creation and installation")
        print("      The entity may create and install new skills without approval.")
        print("      WARNING: skills run as Python code with full access to the")
        print("      entity root. Only enable if you trust the entity's judgment.")
        allow_skills = ui.confirm("Authorise?", indent="      ")

        print()
        print("  [3] Cognitive Mesh Interface (CMI) access")
        print("      The entity may connect to other entities via CMI channels.")
        print("      WARNING: CMI allows the entity to send and receive messages")
        print("      from other entities. Ensure you trust the mesh you join.")
        print()
        cmi_items = [
            "none    — No CMI access",
            "private — Private channels only",
            "public  — Public channels only",
            "both    — Private and public channels",
        ]
        cmi_choice = ui.pick_one("CMI access", cmi_items, default_idx=0, indent="      ")
        cmi_scope = cmi_choice.split()[0]

        print()
        print("  [4] Operator memory")
        print("      The entity may save your preferences and information across")
        print("      sessions. The entity will NEVER share your secrets (API keys,")
        print("      tokens, passwords). NOTE: you are also responsible for not")
        print("      sharing secrets directly in conversation — the entity cannot")
        print("      protect what it never receives.")
        allow_memory = ui.confirm("Authorise?", indent="      ")

        print()
        print("  [5] Scope renewal interval")
        print("      These authorisations will expire and the entity will pause")
        print("      until you renew them. Enter 0 to disable expiry.")
        while True:
            renewal_input = ui.ask("Renewal interval in days", "30")
            try:
                renewal_days = int(renewal_input)
                if renewal_days >= 0:
                    break
            except ValueError:
                pass
            ui.print_err("Please enter a non-negative integer.")

        evolve_scope = {
            "autonomous_evolution": allow_evolution,
            "autonomous_skills": allow_skills,
            "cmi_access": cmi_scope,
            "operator_memory": allow_memory,
            "renewal_days": renewal_days,
        }

    # ── Step 4: CPE backend and model ────────────────────────────────────────
    ui.hr("4. CPE backend and model")
    print()
    from ..cpe.base import KNOWN_MODELS, fetch_ollama_models

    allowed_backends = _get_allowed_backends(profile)
    backend = ui.pick_one("Backend", allowed_backends, indent="  ")

    api_key_saved: str | None = None
    if backend == "ollama":
        ollama_models = fetch_ollama_models()
        if ollama_models:
            model = ui.pick_one("Model", ollama_models, indent="  ")
        else:
            model = ui.ask("Model", "llama3.2")
    elif backend == "pairing":
        model_list = KNOWN_MODELS[backend]
        model = ui.pick_one("Model", model_list, indent="  ")
    else:
        model_list = KNOWN_MODELS[backend]
        model = ui.pick_one("Model", model_list, indent="  ")
        env_var = API_KEY_ENV[backend]
        current_key_hint = "already configured" if os.environ.get(env_var) else ""
        default_hint = current_key_hint if current_key_hint else ""
        api_key = ui.ask(f"{env_var} (leave blank to keep)", default_hint)
        if api_key and api_key != current_key_hint:
            save_api_key(entity_root.name, env_var, api_key)
            api_key_saved = env_var

    # ── Step 5: Copy snapshot and create runtime dirs ────────────────────────
    ui.hr("5. Creating entity")
    print()
    entity_root.mkdir(parents=True, exist_ok=True)

    profile_dir = fcp_ref_root / ("fcp-core" if profile == "haca-core" else "fcp-evolve")

    for src, dst_name in [
        (fcp_ref_root / "fcp_base",  "fcp_base"),
        (fcp_ref_root / "skills",    "skills"),
        (fcp_ref_root / "hooks",     "hooks"),
        (fcp_ref_root / "tests",     "tests"),
        (fcp_ref_root / "boot.md",   "boot.md"),
        (profile_dir / "persona",    "persona"),
    ]:
        dst = entity_root / dst_name
        if not src.exists(): continue
        if src.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"))
        elif src.is_file():
            shutil.copy2(src, dst)

    # ── Step 6: Marker and Runtime dirs ──────────────────────────────────────
    entity_marker = {
        "version": fcp_version,
        "profile": profile,
        "haca_profile": haca_profile,
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    (entity_root / ".fcp-entity").write_text(json.dumps(entity_marker, indent=2), encoding="utf-8")

    fcp_cli_src = fcp_ref_root / "fcp"
    if fcp_cli_src.exists():
        fcp_cli_dst = entity_root / "fcp"
        shutil.copy2(fcp_cli_src, fcp_cli_dst)
        fcp_cli_dst.chmod(0o755)

    for d in [
        entity_root / "memory" / "episodic",
        entity_root / "memory" / "semantic",
        entity_root / "memory" / "active_context",
        entity_root / "state" / "sentinels",
        entity_root / "state" / "snapshots",
        entity_root / "state" / "operator_notifications",
        entity_root / "io" / "inbox" / "presession",
        entity_root / "io" / "spool",
    ]:
        d.mkdir(parents=True, exist_ok=True)
    (Path("/tmp") / "fcp-stage" / entity_root.name).mkdir(parents=True, exist_ok=True)

    defaults_path = profile_dir / "defaults" / "baseline.json"
    baseline = read_json(defaults_path) if defaults_path.exists() else {}
    baseline["entity_id"] = entity_root.name
    baseline["fcp_version"] = fcp_version
    baseline["haca_version"] = "HACA-Arch-1.0.0"
    baseline["haca_profile"] = haca_profile
    baseline["cpe"] = {"backend": backend, "model": model, "topology": "transparent"}
    if profile == "haca-evolve":
        baseline["evolve"] = {"scope": evolve_scope}

    atomic_write(entity_root / "state" / "baseline.json", baseline)
    atomic_write(entity_root / "state" / "integrity.json", {
        "version": "1.0", "algorithm": "sha256",
        "last_checkpoint": None, "files": {},
    })
    for p in [
        entity_root / "state" / "integrity_chain.jsonl",
        entity_root / "state" / "integrity.log",
        entity_root / "memory" / "session.jsonl",
    ]:
        p.write_text("", encoding="utf-8")
    atomic_write(entity_root / "memory" / "working-memory.json", {"entries": []})

    # ── Git init + initial commit ────────────────────────────────────────────
    git_init = False
    if not (entity_root / ".git").exists():
        print()
        git_init = ui.confirm("Initialise a git repository in the entity root?", default=True)

    git_ok = False
    if git_init:
        try:
            subprocess.run(["git", "init", str(entity_root)], check=True, capture_output=True)
            write_entity_gitignore(entity_root)
            subprocess.run(["git", "-C", str(entity_root), "add", "."], check=True, capture_output=True)
            subprocess.run(
                ["git", "-C", str(entity_root), "commit", "-m",
                 f"chore: init entity (fcp v{fcp_version}, {haca_profile})"],
                check=True, capture_output=True,
            )
            git_ok = True
        except subprocess.CalledProcessError as exc:
            print(f"  [!] git failed: {exc.stderr.decode().strip()}")
        except FileNotFoundError:
            print("  [!] git not found — skipping.")

    # ── Step 7: Set as default if first entity ───────────────────────────────
    was_default = get_default_entity() == entity_id
    if not was_default and not list_entities():
        set_default_entity(entity_id)
        was_default = True
    elif not get_default_entity():
        set_default_entity(entity_id)
        was_default = True

    # ── Step 8: Summary ──────────────────────────────────────────────────────
    print()
    ui.hr()
    print(f"  Entity created successfully")
    ui.hr()
    print(f"  entity:       {entity_id}")
    print(f"  path:         {entity_root}")
    print(f"  profile:      {haca_profile}")
    print(f"  fcp version:  v{fcp_version}")
    print(f"  backend:      {backend} / {model}")
    if api_key_saved:
        print(f"  api key:      saved ({api_key_saved})")
    if git_init:
        print(f"  git:          {'initial commit created' if git_ok else 'init failed (see above)'}")
    if profile == "haca-evolve":
        print(f"  scope:")
        print(f"    autonomous evolution:  {'yes' if evolve_scope['autonomous_evolution'] else 'no'}")
        print(f"    autonomous skills:     {'yes' if evolve_scope['autonomous_skills'] else 'no'}")
        print(f"    cmi access:            {evolve_scope['cmi_access']}")
        print(f"    operator memory:       {'yes' if evolve_scope['operator_memory'] else 'no'}")
        renewal = evolve_scope['renewal_days']
        print(f"    renewal:               {'every ' + str(renewal) + ' days' if renewal > 0 else 'disabled'}")
    ui.hr()
    print()
    print(f"  First boot will run FAP (First Activation Protocol).")
    if was_default:
        print(f"  Run:  fcp")
    else:
        print(f"  Run:  fcp set {entity_id} && fcp")
    print()
